lines: AUTO
limit: 3
streamers:
  "/content/drive/MyDrive/zzqlyzgsh2/*.mp4":
    copyright: 1 ### 1为自制，2为转载
    tid: 228 # 投稿分区 https://api.bilibili.com/x/web-interface/view?bvid=BV1YaNNzeE3d 从已知的视频的分类中获取
    # cover: "" # 视频封面
    title: "专制权力与中国社会(有声书)"
    desc: "https://book.douban.com/subject/1326771/"
    tags:
      - "有声书"
    dtime: ~
    extra_fields: '{"watermark": {"state": 0}}' #关闭水印
    # extra-fields '{"is_only_self":1}' #仅自己可见
    open_subtitle: false
